# Assignment 1

These assignments are related to **NumPy** library.
In these assignments, you must program some new code, but also the already given code is used in the assignments.
* Read the related course material before doing the assignments from the
[Topic 1. Introduction to NumPy library](https://ttc8040.pages.labranet.jamk.fi/da_vi_material/lectures/topic1_numpy_basics.nbconvert/).

General notes of assignments:
* NOTE! In general, after the implementation of the function, all assignments have a test program for the function.
* NOTE! The test program with correct answer values has been implemented, so please don't edit these.
* NOTE! Add your code in the assignments only after the TODO lines.


In [161]:
# Write your information here!
student_name = 'Jayani Kothalawala'
student_id = 'AD9680'

## Assignment 01-01. Cumulative sums (1p)

Let's calculate cumulative sums for matrices.

Calculate
1. the cumulative row sum for matrix a (`a_data`) and
2. the cumulative column sum for matrix b (`b_data`).

Before setting the `result` variable, change the both data types to the `list` with the cumulative row sum of matrix `a_data`
(only the last row containing the sum of all values) in the first element and the cumulative column sum of matrix `b_data` in the second element.

```result=[a_cumsum_last_row_as_list, b_cumsum_last_row_as_list]```


Hint `axis` property.

In [162]:
import numpy as np

correct_numpy_01_01 = [[11, 17, 23, 29, 35, 41, 47, 53, 59, 65], [21, 43, 66, 90, 115, 141, 168, 196, 225, 265]]

a_data = [(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), (10, 15, 20, 25, 30, 35, 40, 45, 50, 55)]
b_data = [(11, 12, 13, 14, 15, 16, 17, 18, 19, 20), (21, 22, 23, 24, 25, 26, 27, 28, 29, 40)]



# TODO: Implementation to create result variable

a_data_list = np.array(a_data,dtype=list)
a_cumsum_last_row_as_list = a_data_list.cumsum(axis=0)[-1,:]

b_data_list = np.array(b_data,dtype=list)
b_cumsum_last_row_as_list = b_data_list.cumsum(axis=1)[-1,:]

result = [a_cumsum_last_row_as_list, b_cumsum_last_row_as_list]  # TODO: the result variable should contain your assignment's response
# The Test Program includes automatic checking of the answer. Don't Edit it!
print(result)

try:
    np.testing.assert_array_equal(result, correct_numpy_01_01)
    print('Result was OK')
except AssertionError as err_msg:
    print(err_msg)

[array([11, 17, 23, 29, 35, 41, 47, 53, 59, 65], dtype=object), array([21, 43, 66, 90, 115, 141, 168, 196, 225, 265], dtype=object)]
Result was OK


## Assignment 01-02. Matrix product (1p)

Calculate matrix product for given matrices.

You should create two new matrices (`vec_a`, `vec_b`) including 21 values.
* Matrix `vec_a` should contain values from 1 to 41 with step 2 (1, 3, 5, 7, ..., 41 etc.)
* Matrix `vec_b` should contain values from 100 to 200 with step 5 (100, 105, 110, ..., 200 etc.)

Convert the matrices to a form where the first matrix `a` has 3 rows and 7 columns (`3*7` matrix), and the second matrix `b` has 7 rows and 3 columns (`7*3` matrix).

Calculate the matrix product and store the results in a two-dimensional list (`result`):
* the first element contains `a@b`
* the second element contains `b@a`.

The `result` should include two matrix products as `list`: `[a@b_as_list, b@a_as_list]`.


In [163]:
import numpy as np

correct_01_02 = [[[7945, 8190, 8435], [22155, 22890, 23625], [36365, 37590, 38815]],
                 [[4865, 5495, 6125, 6755, 7385, 8015, 8645], [5540, 6260, 6980, 7700, 8420, 9140, 9860],
                  [6215, 7025, 7835, 8645, 9455, 10265, 11075], [6890, 7790, 8690, 9590, 10490, 11390, 12290],
                  [7565, 8555, 9545, 10535, 11525, 12515, 13505], [8240, 9320, 10400, 11480, 12560, 13640, 14720],
                  [8915, 10085, 11255, 12425, 13595, 14765, 15935]]]

vec_a = np.arange(1,43,2)
vec_b = np.arange(100,205,5)

  # TODO: the result variable should contain your assignment's response

# TODO: Implementation to create result variable
a = vec_a.reshape(3,7)
b = vec_b.reshape(7,3)
first_product = a@b
a_b_as_list = np.array(first_product,dtype=list)
second_product = b@a
b_a_as_list = np.array(second_product,dtype=list)

result = [a_b_as_list, b_a_as_list]
# The Test Program includes automatic checking of the answer. Don't Edit it!
try:
    print(result)
    np.testing.assert_array_equal(result[0], correct_01_02[0])
    np.testing.assert_array_equal(result[1], correct_01_02[1])
    print('Result was OK')
except AssertionError as err_msg:
    print(err_msg)

[array([[7945, 8190, 8435],
       [22155, 22890, 23625],
       [36365, 37590, 38815]], dtype=object), array([[4865, 5495, 6125, 6755, 7385, 8015, 8645],
       [5540, 6260, 6980, 7700, 8420, 9140, 9860],
       [6215, 7025, 7835, 8645, 9455, 10265, 11075],
       [6890, 7790, 8690, 9590, 10490, 11390, 12290],
       [7565, 8555, 9545, 10535, 11525, 12515, 13505],
       [8240, 9320, 10400, 11480, 12560, 13640, 14720],
       [8915, 10085, 11255, 12425, 13595, 14765, 15935]], dtype=object)]
Result was OK


## Assignment 01-03. Rolling Dices (1p)

Let's learn how to generate random numbers using the NumPy library and rolling several dice.

Roll four dices and roll each one a million times.
Then calculate the following four cases and place them in the list of results in order. Round the result to one decimal place.

1. When throwing four dice, the probability that all numbers of the dice are different is approx. **27.8%**.
2. When throwing four dice, the probability that not all numbers of the dice (so two or more dice are same) are different is approx. **72.2%**.
3. When throwing four dice, the probability that at least three number of the dice are same is approx. **9.7%**.
4. When throwing four dice, the probability that four numbers of the dice are same is approx. **0.5%**.

How to implement?
* Implement your own code in the `roll_dice()` function
* Use NumPy's `randint` function to create a **NumPy array** with **1,000,000** random integers between *1-6*.
* Make a NumPy boolean array with `True` (or `1`) value when the condition is `True`, and `False` (or `0`) if not.

Hint! Count how many `True` elements there are in the NumPy array and divide it by the number of elements. This way you can calculate the proportion of all the values in the NumPy array.


In [4]:
import numpy as np

# [share_of_all_are_different, share_of_some_same_values, share_of_three_same, share_of_all_same]
correct_01_03 = [27.8, 72.2, 9.7, 0.5]


def roll_dice(rolls):
    np.random.seed(1050)
    dice_rolls = np.random.randint(7, size=(rolls,4))
    
    print(dice_rolls)
    
    if dice_rolls[0] == dice_rolls[1] == dice_rolls[2] == dice_rolls[3]:
        print("True")
    else:
        print("error")
    dice1, dice2, dice3, dice4 = 0,0,0,0
    
    
    result = np.array([0, 0, 0, 0])  # TODO: the result variable should contain your assignment's response

    # TODO: Implementation to create result variable
    


# The Test Program includes automatic checking of the answer. Don't Edit it!

rolls = 1000000  # 1 million throws
result = roll_dice(rolls)

try:
    print(result)
    np.testing.assert_array_equal(result, correct_01_03)
    print('Result was OK')
except AssertionError as err_msg:
    print(err_msg)

[[4 2 1 2]
 [0 0 1 6]
 [0 5 5 2]
 ...
 [6 6 5 0]
 [1 6 2 4]
 [3 1 3 0]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Assignment 01-04. Scaling values (1p)

Scaling a list of values to certain intervals is a typical operation in machine learning applications.

Do your implementation in the `scale_values()` function.
Scale the values in the given NumPy array (`np.arange(start=10, stop=100, step=4)`) in the range `[-2, 2]`.
* The values are given in the NumPy array `orig_arr` and should therefore be scaled evenly between `[-2, 2]`.
* The smallest value of the resulting array is `-2`, and the largest value is `2`. The other numbers are evenly distributed in this interval (relative to the smallest and largest value).

From the scaled list, calculate the following values into the list:
1. average
2. median
3. The fifth element in the list
4. standard deviation

Note! `result_arr` should include `[average, median, 5th_element, standard deviation]`.
Finally, round the obtained results to four (**4**) decimal places.

Tip: You can use `np.min` and `np.max` functions to implement scaling.

In [29]:
import numpy as np

correct_01_04 = [-0.0, 0.0, -1.2727, 1.206]


def scale_values(arr, first_val, last_val):
     # TODO: the result_arr should contain your assignment's response
    # TODO: Implementation to create result_arr variable
   
    min_val = np.min(arr,axis=0)
    max_val = np.max(arr,axis=0)
    rng = max_val - min_val

    scaled_points = first_val + ((arr - min_val) * (last_val - first_val) / rng)
    average = np.round(np.mean(scaled_points), 4)
    median = np.round(np.median(scaled_points), 4)
    fifth_element = np.round(scaled_points[4], 4)
    std = np.round(np.std(scaled_points), 4)
    result_arr = np.array([average, median, fifth_element, std]) 
    
    
    return result_arr


# The Test Program includes automatic checking of the answer. Don't Edit it!
orig_arr = np.arange(start=10, stop=100, step=4)
result = scale_values(orig_arr, -2, 2)

try:
    print(result)
    np.testing.assert_array_equal(result, correct_01_04)
    print('Result was OK')
except AssertionError as err_msg:
    print(err_msg)

[-0.      0.     -1.2727  1.206 ]
Result was OK


## Assignment 01-05. Replacing missing values in a NumPy Array (1p)

Let's *replace* some values in NumPy array.
 
You should programmatically implement modification to a NumPy array. Implement these in the `replace_values()` function.
* First convert all `NaN` values in the NumPy Array to value zero.
* From the NumPy array, replace all values greater than _75_ and set their value to _75_.
* From the NumPy array, replace all values less than _-75_ and set their value to _-75_.

After that, calculate the matrix product for matrix `a` and to the _inverted_ matrix `b`.


In [ ]:
import numpy as np


correct_01_05 = 5705


def replace_values(tmp_arr):
    # TODO: Implementation to modify tmp_arr argument
    tmp_arr = np.nan_to_num(tmp_arr)
    
    
    tmp_arr[tmp_arr > 75] = 75
    tmp_arr[tmp_arr < -75] = -75
    
    return tmp_arr


# The Test Program includes automatic checking of the answer. Don't Edit it!
a_arr = np.array([12, 25, -32, np.nan, 56, 63, 75, np.nan, 88, -91, np.nan])
b_arr = np.array([60, 45, -42, 86, 61, 79, np.nan, -83, np.nan, 94, np.nan]).T

a_arr = replace_values(a_arr)
b_arr = replace_values(b_arr)
print(a_arr)
print(b_arr)
result = a_arr @ b_arr

try:
    print(result)
    np.testing.assert_array_equal(result.astype('int'), correct_01_05)
    print('Result was OK')
except AssertionError as err_msg:
    print(err_msg)

[ 12.  25. -32.   0.  56.  63.  75.   0.  75. -75.   0.]
[ 60.  45. -42.  75.  61.  75.   0. -75.   0.  75.   0.]
[ 12.  25. -32.   0.  56.  63.  75.   0.  75. -75.   0.]
[ 60.  45. -42.  75.  61.  75.   0. -75.   0.  75.   0.]
5705.0
Result was OK
